# Generated by Django 4.2.21 on 2025-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_total_order_status_order_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.ImageField(blank='true', null='true', upload_to='categories/'),
            preserve_default='true',
        ),
    ]
