# Generated by Django 4.2.21 on 2025-08-28 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='parents',
            field=models.ForeignKey(blank='true', null='true', on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='store.productcategory'),
            preserve_default='true',
        ),
    ]
